export const Routes = {
  LOGIN: '/login',
  VERIFY: '/verify',
  ONBOARDING: '/onboarding',

  HOME: '/',
  STYLIST: '/stylist',
  WARDROBE: '/wardrobe',
  PROFILE: '/profile',

  SEARCH: '/search',
  CLOTHING_DETAIL: '/clothing/[id]',
  AVATAR_CREATE: '/avatar/create',
  AVATAR_EDIT: '/avatar/edit',
  AVATAR_SHOWCASE: '/avatar/showcase',
  COMMUNITY: '/community',
  COMMUNITY_POST: '/community/[postId]',
  COMMUNITY_CREATE: '/community/create',
  USER_PROFILE: '/community/user/[userId]',
  MESSAGES: '/messages',
  MESSAGE_CHAT: '/messages/[chatId]',
  CUSTOMIZE_EDITOR: '/customize/editor',
  CUSTOMIZE_PREVIEW: '/customize/preview',
  CUSTOMIZE_ORDERS: '/customize/orders',
  CUSTOMIZE_ORDER_DETAIL: '/customize/orders/[orderId]',
  MARKET: '/market',
  MARKET_DESIGN: '/market/[designId]',
  BESPOKE: '/bespoke',
  BESPOKE_STUDIO: '/bespoke/[studioId]',
  BESPOKE_SUBMIT: '/bespoke/submit',
  BESPOKE_CHAT: '/bespoke/chat/[orderId]',
  BESPOKE_QUOTE: '/bespoke/quote/[orderId]',
  BESPOKE_ORDERS: '/bespoke/orders',
  ACTIONS: '/actions',
  SETTINGS: '/settings',
  SETTINGS_PREFERENCES: '/settings/preferences',
  SETTINGS_PRIVACY: '/settings/privacy',
} as const;

export type RouteKey = keyof typeof Routes;
export type RoutePath = (typeof Routes)[RouteKey];
