import { DocumentBuilder } from "@nestjs/swagger";

export function createSwaggerConfig() {
  const builder = new DocumentBuilder()
    .setTitle("寻裳 API")
    .setDescription("智能私人形象定制与服装设计助手平台 API")
    .setVersion("1.0")
    .addServer("http://localhost:3001", "dev")
    .addServer("https://staging-api.xuno.app", "staging")
    .addServer("https://api.xuno.app", "production")
    .addBearerAuth()
    .addApiKey(
      { type: "apiKey", name: "x-api-key", in: "header", description: "ML服务API密钥" },
      "x-api-key",
    )
    .addTag("auth", "认证相关接口 - 登录、注册、密码重置")
    .addTag("users", "用户管理 - 用户信息、设置")
    .addTag("profile", "形象档案 - 个人形象数据管理")
    .addTag("photos", "照片管理 - 上传、分析用户照片")
    .addTag("clothing", "服装商品 - 服装浏览、搜索")
    .addTag("try-on", "虚拟试衣 - AI 试衣功能")
    .addTag("recommendations", "风格推荐 - 个性化推荐")
    .addTag("customization", "私人定制 - 定制服务")
    .addTag("search", "搜索功能 - 全局搜索")
    .addTag("favorites", "收藏功能 - 收藏管理")
    .addTag("brands", "品牌管理 - 品牌信息")
    .addTag("analytics", "数据分析 - 用户行为分析")
    .addTag("subscription", "订阅管理 - 会员订阅")
    .addTag("notification", "通知系统 - 消息通知")
    .addTag("privacy", "隐私设置 - 隐私管理")
    .addTag("merchant", "商家后台 - 商家管理")
    .addTag("ai-stylist", "AI造型师 - AI 咨询服务")
    .addTag("payment", "支付系统 - 支付、退款")
    .addTag("ai-safety", "AI安全 - 内容审核与过滤")
    .addTag("code-rag", "代码RAG - 代码语义搜索（供云端AI获取项目上下文）")
    .addTag("health", "健康检查 - 系统状态")
    .addTag("community", "社区 - 用户社区互动")
    .addTag("order", "订单管理 - 订单查询与管理")
    .addTag("cart", "购物车 - 购物车管理")
    .addTag("addresses", "地址管理 - 收货地址")
    .addTag("ai", "AI服务 - 通用AI能力")
    .addTag("style-profiles", "风格档案 - 风格偏好管理")
    .addTag("weather", "天气服务 - 天气数据与穿搭建议")
    .addTag("style-quiz", "风格测试 - 风格问答")
    .addTag("share-template", "分享模板 - 穿搭分享")
    .addTag("wardrobe-collection", "衣橱合集 - 衣橱管理")
    .addTag("consultant", "顾问服务 - 专业顾问咨询")
    .addTag("chat", "聊天 - 实时聊天")
    .addTag("feature-flags", "功能开关 - 功能特性管理")
    .addTag("demo", "演示 - 演示功能")
    .addTag("metrics", "指标 - 系统指标监控")
    .addTag("queue", "队列 - 任务队列管理")
    .addTag("poster", "海报 - 用户画像海报生成")
    .addTag("photo-quality", "照片质量 - 照片质量检测与增强")
    .addTag("onboarding", "新手引导 - 用户注册引导流程")
    .addTag("ws", "WebSocket - 实时通信")
    .addTag("cache", "缓存 - 缓存管理")
    .addTag("database", "数据库 - 数据库管理");

  return builder.build();
}
