apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aineed-network-policy
  namespace: aineed
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: aineed
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
    - ports:
        - protocol: TCP
          port: 3001
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
    - to:
        - namespaceSelector:
            matchLabels:
              name: aineed
