import { primitiveTokens } from "./generated/primitive-tokens";
import { semanticTokens } from "./generated/semantic-tokens";

const brand = primitiveTokens.colors.brand;
const neutral = primitiveTokens.colors.neutral;
const status = semanticTokens.colors.status;

export const DesignTokens = {
  colors: {
    brand: {
      terracotta: brand.terracotta[500],
      terracottaLight: brand.terracotta[300],
      terracottaDark: brand.terracotta[700],
      sage: brand.sage[500],
      sageLight: brand.sage[300],
      sageDark: brand.sage[700],
      camel: brand.camel[500],
      camelLight: brand.camel[300],
      camelDark: brand.camel[700],
      slate: brand.slate[500],
      slateLight: brand.slate[300],
      slateDark: brand.slate[700],
    },
    neutral: {
      white: neutral.white,
      50: neutral[50],
      100: neutral[100],
      200: neutral[200],
      300: neutral[300],
      400: neutral[400],
      500: neutral[500],
      600: neutral[600],
      700: neutral[700],
      800: neutral[800],
      900: neutral[900],
      black: neutral.black,
    },
    semantic: {
      success: status.success.light,
      successLight: status.success.lightBg,
      successDark: "#1B7A3D",
      warning: status.warning.light,
      warningLight: status.warning.lightBg,
      warningDark: "#8B6914",
      error: status.error.light,
      errorLight: status.error.lightBg,
      errorDark: "#A12525",
      info: status.info.light,
      infoLight: status.info.lightBg,
      like: "#FF4757",
      bookmark: "#F1C40F",
      chartGood: "#4CAF50",
      chartMedium: "#FF9800",
      chartPoor: "#F44336",
      chartGrid: "#E0E0E0",
      skeletonBase: "rgba(196, 149, 106, 0.2)",
      skeletonShimmer: "rgba(196, 149, 106, 0.4)",
      warmBlush: "#F5D5C5",
      slateMist: "#B8C5D1",
      goldenGlow: "#F5D89A",
      sageMist: "#9DC4B5",
      yellow: "#EAB308",
      brown: "#92400E",
      wechat: "#07C160",
      weibo: "#E6162D",
      qq: "#12B7F5",
      mutedSage: "#6E7A62",
      gold: "#D4A853",
      ocean: "#4A90D9",
      mint: "#7ED4AD",
      coral: "#FF7F7F",
      oceanMint: "#5BB5A2",
      purple: "#9B59B6",
      warmAccent: "#E8A87C",
      coralRose: "#FF6B6B",
      oceanDeepLight: "#33AAFF",
      oceanDeepMain: "#167FFB",
    },
    fashion: {
      camel: "#C19A6B",
      olive: "#808000",
      rust: "#B7410E",
      mustard: "#FFDB58",
      pumpkin: "#FF7518",
      burgundy: "#722F37",
      royalBlue: "#4169E1",
      emerald: "#50C878",
      deepPurple: "#301934",
      lightPink: "#FFB6C1",
      darkBrown: "#654321",
      armyGreen: "#4B5320",
      deepMagenta: "#4A0028",
      iceBlue: "#99FFFF",
      cornflower: "#6495ED",
      neon: "#CCFF00",
      navy: "#000080",
      orange: "#FF6B00",
      vividGreen: "#00C853",
      deepViolet: "#7B1FA2",
      mediumGray: "#808080",
      darkGray: "#4A4A4A",
      terracottaMid: "#C6775C",
      forestGreen: "#2D5016",
    },
    backgrounds: {
      primary: neutral.white,
      secondary: neutral[50],
      tertiary: neutral[100],
      elevated: neutral.white,
      overlay: "rgba(0, 0, 0, 0.4)",
      cartLight: "#FFF5F0",
    },
    text: {
      primary: neutral[900],
      secondary: neutral[600],
      tertiary: neutral[500],
      inverse: neutral.white,
      brand: "#8A4E32",
    },
    borders: {
      light: "rgba(0, 0, 0, 0.06)",
      default: "rgba(0, 0, 0, 0.1)",
      strong: "rgba(0, 0, 0, 0.2)",
      brand: brand.terracotta[500],
    },
    colorSeasons: {
      spring: {
        label: "春季型",
        colors: ["#FF6B6B", "#FFA07A", "#FFD700", "#98FB98"],
        bg: "#FFF5F0",
      },
      summer: {
        label: "夏季型",
        colors: ["#87CEEB", "#DDA0DD", "#B0C4DE", "#F0E68C"],
        bg: "#F0F5FF",
      },
      autumn: {
        label: "秋季型",
        colors: ["#D2691E", "#B8860B", "#8B4513", "#CD853F"],
        bg: "#FFF8F0",
      },
      winter: {
        label: "冬季型",
        colors: ["#1A1A2E", "#E94560", "#FFFFFF", "#C0C0C0"],
        bg: "#F5F5FA",
      },
    },
    xuno: {
      warmCamel: "#C4956A",
      warmCamelLight: "#D4A882",
      warmCamelDark: "#A87B52",
      charcoal: "#2D3436",
      warmOrange: "#E17055",
      main: "#C67C4E",
      light: "#F5E6D3",
      dark: "#8B5E3C",
    },
    funnel: {
      l1: "#E8DDD5",
      l2: "#D4C4B5",
      l3: "#C0AA95",
      l4: "#AB9075",
      l5: "#977655",
      l6: "#C67B5C",
    },
  },

  gradients: {
    brand: [brand.terracotta[500], brand.camel[500]],
    brandSoft: ["rgba(196, 69, 54, 0.1)", "rgba(181, 160, 140, 0.1)"],
    sage: [brand.sage[500], brand.slate[500]],
    hero: [neutral[50], neutral.white],
    card: [neutral.white, neutral[50]],
    warm: [brand.terracotta[500], "#D9A441"],
    cool: [brand.sage[500], brand.slate[500]],
    warmAccent: ["#C67C4E", "#E8A87C"],
    coolAccent: ["#4A90D9", "#7ED4AD"],
    heroAccent: ["#C67C4E", "#4A90D9"],
    coralRose: ["#FF7F7F", "#FF6B6B"],
    oceanMint: ["#4A90D9", "#7ED4AD"],
    oceanDeep: ["#167FFB", "#33AAFF"],
  },

  typography: {
    fontFamily: {
      heading: {
        ios: "Georgia",
        android: "serif",
        web: "Georgia, 'Noto Serif SC', serif",
      },
      body: {
        ios: "System",
        android: "sans-serif",
        web: "'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
      },
      mono: {
        ios: "Menlo",
        android: "monospace",
        web: "'Space Mono', monospace",
      },
    },
    sizes: {
      xxs: 10,
      xs: 11,
      sm: 12,
      base: 14,
      md: 16,
      lg: 18,
      xl: 20,
      "2xl": 24,
      "3xl": 30,
      "4xl": 36,
      "5xl": 48,
      "6xl": 60,
    },
    lineHeights: {
      tight: 1.2,
      snug: 1.35,
      normal: 1.5,
      relaxed: 1.65,
      loose: 1.8,
    },
    fontWeights: {
      light: "300" as const,
      regular: "400" as const,
      medium: "500" as const,
      semibold: "600" as const,
      bold: "700" as const,
    },
    letterSpacing: {
      tight: -0.5,
      normal: 0,
      wide: 0.5,
      wider: 1,
      widest: 2,
    },
  },

  spacing: {
    0: 0,
    px: 1,
    0.5: 2,
    1: 4,
    1.5: 6,
    2: 8,
    2.5: 10,
    3: 12,
    3.5: 14,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 44,
    12: 48,
    14: 56,
    16: 64,
    20: 80,
    24: 96,
    32: 128,
  },

  borderRadius: {
    none: 0,
    xs: 2,
    sm: 4,
    md: 6,
    lg: 12,
    xl: 16,
    "2xl": 24,
    "3xl": 32,
    full: 9999,
  },

  shadows: {
    none: {
      shadowColor: "transparent",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    xs: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.04,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 8,
    },
    xl: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.12,
      shadowRadius: 24,
      elevation: 12,
    },
    brand: {
      shadowColor: brand.terracotta[500],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
      elevation: 6,
    },
  },

  animation: {
    duration: {
      instant: 100,
      fast: 200,
      normal: 300,
      slow: 500,
      slower: 800,
    },
    easing: {
      easeInOut: [0.4, 0, 0.2, 1],
      easeOut: [0, 0, 0.2, 1],
      easeIn: [0.4, 0, 1, 1],
      spring: { damping: 15, stiffness: 150, mass: 1 },
      gentle: { damping: 20, stiffness: 100, mass: 1 },
    },
  },

  breakpoints: {
    sm: 640,
    md: 768,
    lg: 1024,
    xl: 1280,
    "2xl": 1536,
  },

  motif: {
    patterns: {
      weave: {
        strokeColor: brand.terracotta[500],
        strokeWidth: 1,
        opacity: 0.06,
        spacing: 24,
      },
      terracottaWave: {
        strokeColor: brand.terracotta[500],
        strokeWidth: 1.5,
        opacity: 0.08,
        amplitude: 8,
        wavelength: 40,
      },
      sageLeaf: {
        fillColor: brand.sage[500],
        opacity: 0.05,
        size: 20,
        spacing: 32,
      },
    },
    ornaments: {
      cornerRadius: 16,
      strokeWidth: 1.5,
      opacity: 0.12,
      color: brand.terracotta[500],
    },
  },
} as const;

export type DesignTokensType = typeof DesignTokens;

export const darkTokens = {
  colors: {
    brand: {
      terracotta: brand.terracotta[300],
      terracottaLight: brand.terracotta[200],
      terracottaDark: brand.terracotta[500],
      sage: brand.sage[300],
      sageLight: brand.sage[200],
      sageDark: brand.sage[600],
      camel: brand.camel[300],
      camelLight: brand.camel[200],
      camelDark: brand.camel[600],
      slate: brand.slate[300],
      slateLight: brand.slate[200],
      slateDark: brand.slate[600],
    },
    neutral: {
      white: neutral.black,
      50: neutral[900],
      100: neutral[800],
      200: neutral[700],
      300: neutral[600],
      400: neutral[400],
      500: neutral[300],
      600: neutral[200],
      700: neutral[100],
      800: neutral[50],
      900: neutral[50],
      black: neutral.white,
    },
    semantic: {
      success: status.success.dark,
      successLight: status.success.darkBg,
      successDark: "#2D8A4E",
      warning: status.warning.dark,
      warningLight: status.warning.darkBg,
      warningDark: "#D9A441",
      error: status.error.dark,
      errorLight: status.error.darkBg,
      errorDark: "#D45546",
      info: status.info.dark,
      infoLight: status.info.darkBg,
      like: "#FF6B7A",
      bookmark: "#F5D44A",
      chartGood: "#6BCB77",
      chartMedium: "#FFB347",
      chartPoor: "#FF6B6B",
      chartGrid: "#3D3D39",
      skeletonBase: "rgba(196, 149, 106, 0.15)",
      skeletonShimmer: "rgba(196, 149, 106, 0.3)",
      warmBlush: "#8B6F5E",
      slateMist: "#96A6B5",
      goldenGlow: "#E8C87A",
      sageMist: "#9DAA90",
      yellow: "#F5C842",
      brown: "#B8763E",
      wechat: "#07C160",
      weibo: "#E6162D",
      qq: "#12B7F5",
      mutedSage: "#8B9A7D",
      gold: "#E8C87A",
      ocean: "#5A88B3",
      mint: "#4A9E84",
      coral: "#996464",
      oceanMint: "#5EB89C",
      purple: "#B07CC8",
      warmAccent: "#D4917A",
      coralRose: "#B37A7A",
      oceanDeepLight: "#89B5D6",
      oceanDeepMain: "#5A88B3",
    },
    fashion: DesignTokens.colors.fashion,
    backgrounds: {
      primary: "#161412",
      secondary: "#1C1916",
      tertiary: "#222018",
      elevated: "#1F1B18",
      overlay: "rgba(0, 0, 0, 0.72)",
      cartLight: "#2D1A14",
    },
    text: {
      primary: "#F5F2ED",
      secondary: "#B8B0A8",
      tertiary: "#9B958E",
      inverse: "#191613",
      brand: "#D68B6C",
    },
    borders: {
      light: "rgba(255, 255, 255, 0.06)",
      default: "rgba(255, 255, 255, 0.1)",
      strong: "rgba(255, 255, 255, 0.18)",
      brand: "#D68B6C",
    },
    colorSeasons: DesignTokens.colors.colorSeasons,
    xuno: DesignTokens.colors.xuno,
    funnel: DesignTokens.colors.funnel,
  },
  gradients: {
    brand: [brand.terracotta[300], brand.camel[300]],
    brandSoft: ["rgba(214, 139, 108, 0.15)", "rgba(201, 184, 166, 0.15)"],
    sage: [brand.sage[300], brand.slate[300]],
    hero: [neutral[900], "#161412"],
    card: ["#1F1B18", neutral[900]],
    warm: [brand.terracotta[300], "#E8B451"],
    cool: [brand.sage[300], brand.slate[300]],
    warmAccent: [brand.terracotta[300], "#D4917A"],
    coolAccent: ["#5A88B3", "#4A9E84"],
    heroAccent: [brand.terracotta[300], "#5A88B3"],
    coralRose: ["#996464", "#B37A7A"],
    oceanMint: ["#5A88B3", "#4A9E84"],
    oceanDeep: ["#5A88B3", "#89B5D6"],
  },
  typography: DesignTokens.typography,
  spacing: DesignTokens.spacing,
  borderRadius: DesignTokens.borderRadius,
  shadows: {
    none: DesignTokens.shadows.none,
    xs: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 1,
    },
    sm: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 8,
    },
    xl: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.4,
      shadowRadius: 24,
      elevation: 12,
    },
    brand: {
      shadowColor: brand.terracotta[300],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 12,
      elevation: 6,
    },
  },
  animation: DesignTokens.animation,
  breakpoints: DesignTokens.breakpoints,
  motif: {
    patterns: {
      weave: {
        strokeColor: brand.terracotta[300],
        strokeWidth: 1,
        opacity: 0.08,
        spacing: 24,
      },
      terracottaWave: {
        strokeColor: brand.terracotta[300],
        strokeWidth: 1.5,
        opacity: 0.1,
        amplitude: 8,
        wavelength: 40,
      },
      sageLeaf: {
        fillColor: brand.sage[300],
        opacity: 0.07,
        size: 20,
        spacing: 32,
      },
    },
    ornaments: {
      cornerRadius: 16,
      strokeWidth: 1.5,
      opacity: 0.15,
      color: brand.terracotta[300],
    },
  },
} as const;

export type DarkTokensType = typeof darkTokens;

export const Spacing = DesignTokens.spacing;
export const BorderRadius = DesignTokens.borderRadius;
export const Shadows = DesignTokens.shadows;
export const Typography = DesignTokens.typography;
export const Animation = DesignTokens.animation;
export const Layout = { maxWidth: 768 };
export const ZIndex = {
  base: 0,
  dropdown: 1000,
  sticky: 1100,
  fixed: 1200,
  overlay: 1300,
  modal: 1400,
  popover: 1500,
  toast: 1600,
  tooltip: 1700,
};
