import { Injectable, Logger } from "@nestjs/common";
import * as fs from "fs";
import * as path from "path";

/** Shape of the precache manifest generated by scripts/tts-precache.py */
interface PrecacheManifest {
  voice: string;
  generated_at: string;
  phrases: Record<string, string>;
  phrase_texts: Record<string, string>;
}

/**
 * EdgeTTSService - Gateway to Python Edge-TTS endpoint.
 *
 * NestJS acts as the API gateway. Python FastAPI handles actual audio
 * generation via the edge-tts library. This service calls the Python
 * /tts/synthesize endpoint and returns the audio URL to the mobile client.
 *
 * Per D-11: Supports precache-first lookup for common phrases.
 * Graceful degradation (WKS-04): If Python TTS endpoint is unreachable,
 * callers receive a null audioUrl -- mobile client shows text-only.
 */
@Injectable()
export class EdgeTTSService {
  private readonly logger = new Logger(EdgeTTSService.name);
  private readonly pythonBaseUrl: string;
  private readonly ttsCacheDir: string;
  private manifest: PrecacheManifest | null = null;
  private manifestLoaded = false;

  constructor() {
    this.pythonBaseUrl = process.env.PYTHON_AI_URL || "http://localhost:8000";
    this.ttsCacheDir =
      process.env.TTS_CACHE_DIR || path.join(process.cwd(), "ml", "data", "tts-cache");
  }

  /**
   * Try to retrieve a pre-cached audio file by phrase key.
   * Per D-11: Pre-cache common voice responses to reduce real-time TTS latency.
   *
   * @param textKey - Phrase key matching PRECACHE_PHRASES in scripts/tts-precache.py
   * @returns Audio URL if cached, null if not found
   */
  async getCachedAudio(textKey: string): Promise<string | null> {
    try {
      if (!this.manifestLoaded) {
        await this.loadManifest();
      }

      if (!this.manifest) {
        return null;
      }

      const filename = this.manifest.phrases[textKey];
      if (!filename) {
        this.logger.debug(`No precache entry for key: ${textKey}`);
        return null;
      }

      const filePath = path.join(this.ttsCacheDir, filename);
      if (!fs.existsSync(filePath)) {
        this.logger.debug(`Precache file missing: ${filePath}`);
        return null;
      }

      // Return a URL path that can be served statically
      // In production, this would be a MinIO/CDN URL
      const audioUrl = `/tts-cache/${filename}`;
      this.logger.debug(`Precache hit: ${textKey} -> ${audioUrl}`);
      return audioUrl;
    } catch (error) {
      this.logger.warn(
        `Precache lookup failed: ${error instanceof Error ? error.message : String(error)}`
      );
      return null;
    }
  }

  /**
   * Call Python FastAPI /tts/synthesize endpoint to generate audio.
   * Returns the audio URL served by Python (MinIO or local static).
   */
  async synthesizeAndUpload(text: string, voice = "zh-CN-XiaoxiaoNeural"): Promise<string | null> {
    try {
      const response = await fetch(`${this.pythonBaseUrl}/tts/synthesize`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, voice, rate: "-10%" }),
      });

      if (!response.ok) {
        throw new Error(`TTS synthesis failed: ${response.status}`);
      }

      const data = (await response.json()) as { audio_url: string };
      return data.audio_url;
    } catch (error) {
      this.logger.warn(
        `TTS synthesis failed: ${error instanceof Error ? error.message : String(error)}`
      );
      return null;
    }
  }

  /**
   * Load the precache manifest from disk (lazy, once).
   */
  private async loadManifest(): Promise<void> {
    this.manifestLoaded = true;
    try {
      const manifestPath = path.join(this.ttsCacheDir, "manifest.json");
      if (fs.existsSync(manifestPath)) {
        const raw = fs.readFileSync(manifestPath, "utf-8");
        this.manifest = JSON.parse(raw) as PrecacheManifest;
        this.logger.log(
          `TTS precache manifest loaded: ${Object.keys(this.manifest.phrases).length} phrases`
        );
      }
    } catch (error) {
      this.logger.warn(
        `Failed to load TTS precache manifest: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }
}
