export {
  Gender,
  BodyType,
  ColorSeason,
  ClothingCategory,
  Occasion,
  StyleTag,
  OrderStatus,
  BespokeOrderStatus,
  PostStatus,
  DesignStatus,
  NotificationType,
  InteractionType,
  BudgetRange,
  ProductType,
  Material,
  TryOnStatus,
  OutfitImageStatus,
  ClothingSlot,
  MessageType,
  BespokeQuoteStatus,
  DesignReportStatus,
  PreReviewResult,
  UserRole,
} from './enums';

export type {
  Gender as GenderType,
  BodyType as BodyTypeType,
  ColorSeason as ColorSeasonType,
  ClothingCategory as ClothingCategoryType,
  Occasion as OccasionType,
  StyleTag as StyleTagType,
  OrderStatus as OrderStatusType,
  BespokeOrderStatus as BespokeOrderStatusType,
  PostStatus as PostStatusType,
  DesignStatus as DesignStatusType,
  NotificationType as NotificationTypeType,
  InteractionType as InteractionTypeType,
  BudgetRange as BudgetRangeType,
  ProductType as ProductTypeType,
  Material as MaterialType,
  TryOnStatus as TryOnStatusType,
  OutfitImageStatus as OutfitImageStatusType,
  ClothingSlot as ClothingSlotType,
  MessageType as MessageTypeType,
  BespokeQuoteStatus as BespokeQuoteStatusType,
  DesignReportStatus as DesignReportStatusType,
  PreReviewResult as PreReviewResultType,
  UserRole as UserRoleType,
} from './enums';

export type {
  User,
  UserProfile,
  UserPreferences,
  BodyProfile,
  BodyAnalysisResult,
  Category,
  Brand,
  ClothingItem,
  Outfit,
  OutfitItem,
  ChatSession,
  ChatMessage,
  TryonResult,
  UserInteraction,
  WardrobeItem,
  Favorite,
  StyleRule,
  CommunityPost,
  PostComment,
  UserFollow,
  ChatRoom,
  ChatRoomParticipant,
  DirectMessage,
  Notification,
  AvatarTemplate,
  AvatarParameterDefs,
  ClothingMapEntry,
  UserAvatar,
  CustomDesign,
  DesignData,
  CustomOrder,
  ShippingAddress,
  ProductTemplate,
  DesignLike,
  DesignReport,
  BespokeStudio,
  BespokeOrder,
  BespokeMessage,
  BespokeQuote,
  BespokeReview,
  OutfitImage,
  PreReviewDetail,
  SearchResult,
} from './models';

export type {
  ApiError,
  PaginationMeta,
  ApiResponse,
  PaginatedResponse,
  PaginationDto,
  AuthResponse,
  SendCodeDto,
  VerifyCodeDto,
  RefreshTokenDto,
  UpdateProfileDto,
  UpdatePreferencesDto,
  UpdateBodyProfileDto,
  CreateClothingDto,
  ClothingQueryDto,
  CreateSessionDto,
  SendMessageDto,
  CreateAvatarDto,
  UpdateAvatarDto,
  DressAvatarDto,
  CreateDesignDto,
  UpdateDesignDto,
  DesignQueryDto,
  CreateCustomOrderDto,
  CreateOutfitDto,
  UpdateOutfitDto,
  AddOutfitItemDto,
  AddToWardrobeDto,
  UpdateWardrobeItemDto,
  CreateFavoriteDto,
  CreatePostDto,
  CreateCommentDto,
  CreateRoomDto,
  SendMessageRoomDto,
  CreateBespokeOrderDto,
  CreateBespokeStudioDto,
  UpdateBespokeStudioDto,
  CreateBespokeQuoteDto,
  CreateBespokeReviewDto,
  ReportDesignDto,
  GenerateOutfitImageDto,
  OutfitImageQueryDto,
  RecordInteractionDto,
  AnalyzeBodyDto,
  SearchQueryDto,
  CreateCategoryDto,
  UpdateCategoryDto,
  CreateBrandDto,
  UpdateBrandDto,
  CreateStyleRuleDto,
  UpdateStyleRuleDto,
  CreateProductTemplateDto,
  UpdateProductTemplateDto,
  RecommendationQueryDto,
  QueryRulesDto,
  EmbedTextDto,
  EmbedBatchDto,
  SearchSimilarDto,
  BatchIndexDto,
  UserResponse,
  UserProfileResponse,
  ClothingItemResponse,
  OutfitResponse,
  ChatSessionResponse,
  ChatMessageResponse,
  WardrobeItemResponse,
  CommunityPostResponse,
  PostCommentResponse,
  NotificationResponse,
  AvatarTemplateResponse,
  UserAvatarResponse,
  CustomDesignResponse,
  CustomOrderResponse,
  ProductTemplateResponse,
  BespokeStudioResponse,
  BespokeOrderResponse,
  BespokeMessageResponse,
  BespokeQuoteResponse,
  BespokeReviewResponse,
  OutfitImageResponse,
  FavoriteResponse,
  CategoryResponse,
  BrandResponse,
  StyleRuleResponse,
  DesignReportResponse,
} from './api';
