// @ts-nocheck
import { PrismaClient, PriceRange } from '@prisma/client';

const brands = [
  // === Self-operated ===
  {
    name: '寻裳Studio',
    slug: 'xuno-studio',
    description: '寻裳自营设计师品牌，融合AI科技与时尚美学',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/xuno-studio-logo/200/200',
    verified: true,
  },
  // === Fast Fashion ===
  {
    name: 'ZARA',
    slug: 'zara',
    description: '西班牙快时尚品牌，提供最新潮流服饰',
    priceRange: PriceRange.mid_range,
    website: 'https://www.zara.cn',
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories', 'footwear'],
    logo: 'https://picsum.photos/seed/zara-logo/200/200',
    verified: true,
  },
  {
    name: 'UNIQLO',
    slug: 'uniqlo',
    description: '日本休闲服饰品牌，注重基础款与舒适度',
    priceRange: PriceRange.budget,
    website: 'https://www.uniqlo.cn',
    categories: ['tops', 'bottoms', 'outerwear', 'accessories', 'activewear'],
    logo: 'https://picsum.photos/seed/uniqlo-logo/200/200',
    verified: true,
  },
  {
    name: 'H&M',
    slug: 'hm',
    description: '瑞典快时尚品牌，时尚与可持续并行',
    priceRange: PriceRange.budget,
    website: 'https://www.hm.com',
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/hm-logo/200/200',
    verified: true,
  },
  {
    name: 'GAP',
    slug: 'gap',
    description: '美国休闲服饰品牌，经典美式风格',
    priceRange: PriceRange.mid_range,
    website: 'https://www.gap.cn',
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/gap-logo/200/200',
    verified: true,
  },
  {
    name: 'Pull&Bear',
    slug: 'pull-and-bear',
    description: '年轻潮流品牌，街头休闲风格',
    priceRange: PriceRange.budget,
    categories: ['tops', 'bottoms', 'outerwear', 'footwear'],
    logo: 'https://picsum.photos/seed/pullbear-logo/200/200',
    verified: true,
  },
  {
    name: 'Bershka',
    slug: 'bershka',
    description: '西班牙年轻潮流品牌，前卫设计',
    priceRange: PriceRange.budget,
    categories: ['tops', 'bottoms', 'dresses', 'accessories'],
    logo: 'https://picsum.photos/seed/bershka-logo/200/200',
    verified: true,
  },
  {
    name: 'Mango',
    slug: 'mango',
    description: '西班牙女装品牌，优雅都市风格',
    priceRange: PriceRange.mid_range,
    website: 'https://www.mango.com',
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/mango-logo/200/200',
    verified: true,
  },
  {
    name: 'URBAN REVIVO',
    slug: 'urban-revico',
    description: '中国快时尚品牌，潮流设计高性价比',
    priceRange: PriceRange.budget,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/ur-logo/200/200',
    verified: true,
  },
  {
    name: 'MJstyle',
    slug: 'mjstyle',
    description: '新锐快时尚品牌，年轻活力设计',
    priceRange: PriceRange.budget,
    categories: ['tops', 'bottoms', 'dresses', 'accessories'],
    logo: 'https://picsum.photos/seed/mjstyle-logo/200/200',
    verified: true,
  },
  // === Premium ===
  {
    name: 'COS',
    slug: 'cos',
    description: 'H&M旗下高端品牌，极简主义设计',
    priceRange: PriceRange.premium,
    website: 'https://www.cos.cn',
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/cos-logo/200/200',
    verified: true,
  },
  {
    name: 'Massimo Dutti',
    slug: 'massimo-dutti',
    description: 'Inditex集团高端品牌，精致优雅风格',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/md-logo/200/200',
    verified: true,
  },
  {
    name: 'Sandro',
    slug: 'sandro',
    description: '法国轻奢品牌，巴黎优雅风格',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear'],
    logo: 'https://picsum.photos/seed/sandro-logo/200/200',
    verified: true,
  },
  {
    name: 'Maje',
    slug: 'maje',
    description: '法国轻奢女装品牌，浪漫波西米亚风',
    priceRange: PriceRange.premium,
    categories: ['tops', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/maje-logo/200/200',
    verified: true,
  },
  {
    name: 'Theory',
    slug: 'theory',
    description: '美国高端职场品牌，精致剪裁',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear'],
    logo: 'https://picsum.photos/seed/theory-logo/200/200',
    verified: true,
  },
  {
    name: 'A.P.C.',
    slug: 'apc',
    description: '法国设计师品牌，简约法式风格',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/apc-logo/200/200',
    verified: true,
  },
  // === Sportswear ===
  {
    name: 'Nike',
    slug: 'nike',
    description: '全球领先的运动品牌',
    priceRange: PriceRange.mid_range,
    website: 'https://www.nike.com',
    categories: ['activewear', 'footwear', 'tops', 'bottoms', 'accessories'],
    logo: 'https://picsum.photos/seed/nike-logo/200/200',
    verified: true,
  },
  {
    name: 'Adidas',
    slug: 'adidas',
    description: '德国运动品牌，经典三条杠设计',
    priceRange: PriceRange.mid_range,
    website: 'https://www.adidas.com',
    categories: ['activewear', 'footwear', 'tops', 'bottoms'],
    logo: 'https://picsum.photos/seed/adidas-logo/200/200',
    verified: true,
  },
  {
    name: 'Puma',
    slug: 'puma',
    description: '德国运动品牌，时尚运动融合',
    priceRange: PriceRange.mid_range,
    categories: ['activewear', 'footwear', 'tops', 'accessories'],
    logo: 'https://picsum.photos/seed/puma-logo/200/200',
    verified: true,
  },
  {
    name: 'Under Armour',
    slug: 'under-armour',
    description: '美国专业运动品牌，科技运动装备',
    priceRange: PriceRange.mid_range,
    categories: ['activewear', 'footwear', 'tops', 'bottoms'],
    logo: 'https://picsum.photos/seed/ua-logo/200/200',
    verified: true,
  },
  {
    name: 'Lululemon',
    slug: 'lululemon',
    description: '加拿大高端瑜伽运动品牌',
    priceRange: PriceRange.premium,
    categories: ['activewear', 'tops', 'bottoms', 'accessories'],
    logo: 'https://picsum.photos/seed/lulu-logo/200/200',
    verified: true,
  },
  {
    name: 'FILA',
    slug: 'fila',
    description: '意大利运动时尚品牌，优雅运动风格',
    priceRange: PriceRange.mid_range,
    categories: ['activewear', 'footwear', 'tops', 'bottoms'],
    logo: 'https://picsum.photos/seed/fila-logo/200/200',
    verified: true,
  },
  {
    name: 'ANTA',
    slug: 'anta',
    description: '中国领先运动品牌，专业运动装备',
    priceRange: PriceRange.budget,
    categories: ['activewear', 'footwear', 'tops', 'bottoms'],
    logo: 'https://picsum.photos/seed/anta-logo/200/200',
    verified: true,
  },
  {
    name: 'Li-Ning',
    slug: 'li-ning',
    description: '中国运动品牌，国潮设计先锋',
    priceRange: PriceRange.mid_range,
    categories: ['activewear', 'footwear', 'tops', 'bottoms'],
    logo: 'https://picsum.photos/seed/lining-logo/200/200',
    verified: true,
  },
  // === Chinese Fashion Brands ===
  {
    name: 'Bosideng',
    slug: 'bosideng',
    description: '中国羽绒服领先品牌，专注保暖科技',
    priceRange: PriceRange.mid_range,
    categories: ['outerwear'],
    logo: 'https://picsum.photos/seed/bosideng-logo/200/200',
    verified: true,
  },
  {
    name: 'Peacebird',
    slug: 'peacebird',
    description: '太平鸟，中国时尚女装品牌',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear'],
    logo: 'https://picsum.photos/seed/peacebird-logo/200/200',
    verified: true,
  },
  {
    name: 'GXG',
    slug: 'gxg',
    description: '中国都市男装品牌，年轻商务休闲',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'bottoms', 'outerwear'],
    logo: 'https://picsum.photos/seed/gxg-logo/200/200',
    verified: true,
  },
  {
    name: 'SEMiR',
    slug: 'semir',
    description: '森马，中国休闲服饰品牌',
    priceRange: PriceRange.budget,
    categories: ['tops', 'bottoms', 'outerwear'],
    logo: 'https://picsum.photos/seed/semir-logo/200/200',
    verified: true,
  },
  {
    name: 'Ochirly',
    slug: 'ochirly',
    description: '欧时力，时尚女装品牌',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/ochirly-logo/200/200',
    verified: true,
  },
  {
    name: 'MO&Co.',
    slug: 'mo-co',
    description: '中国设计师女装品牌，酷感摩登',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear'],
    logo: 'https://picsum.photos/seed/moco-logo/200/200',
    verified: true,
  },
  {
    name: 'JNBY',
    slug: 'jnby',
    description: '江南布衣，设计师品牌，自然简约',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'dresses', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/jnby-logo/200/200',
    verified: true,
  },
  {
    name: 'EIN',
    slug: 'ein',
    description: '中国独立设计师品牌，文艺气质',
    priceRange: PriceRange.premium,
    categories: ['tops', 'dresses', 'outerwear'],
    logo: 'https://picsum.photos/seed/ein-logo/200/200',
    verified: true,
  },
  // === Basics/Casual ===
  {
    name: 'Champion',
    slug: 'champion',
    description: '美国经典运动休闲品牌',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'bottoms', 'activewear'],
    logo: 'https://picsum.photos/seed/champion-logo/200/200',
    verified: true,
  },
  {
    name: 'Carhartt',
    slug: 'carhartt',
    description: '美国工装品牌，街头潮流标杆',
    priceRange: PriceRange.mid_range,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/carhartt-logo/200/200',
    verified: true,
  },
  {
    name: "Levi's",
    slug: 'levis',
    description: '美国经典牛仔品牌，牛仔裤发明者',
    priceRange: PriceRange.mid_range,
    categories: ['bottoms', 'tops', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/levis-logo/200/200',
    verified: true,
  },
  {
    name: 'Calvin Klein',
    slug: 'calvin-klein',
    description: '美国时尚品牌，简约现代设计',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/ck-logo/200/200',
    verified: true,
  },
  {
    name: 'Tommy Hilfiger',
    slug: 'tommy-hilfiger',
    description: '美国经典休闲品牌，美式学院风',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/tommy-logo/200/200',
    verified: true,
  },
  // === Shoes ===
  {
    name: 'Dr. Martens',
    slug: 'dr-martens',
    description: '英国鞋履品牌，经典马丁靴',
    priceRange: PriceRange.premium,
    categories: ['footwear'],
    logo: 'https://picsum.photos/seed/drm-logo/200/200',
    verified: true,
  },
  {
    name: 'Converse',
    slug: 'converse',
    description: '美国经典帆布鞋品牌',
    priceRange: PriceRange.budget,
    categories: ['footwear', 'accessories'],
    logo: 'https://picsum.photos/seed/converse-logo/200/200',
    verified: true,
  },
  {
    name: 'Vans',
    slug: 'vans',
    description: '美国极限运动鞋品牌，街头文化代表',
    priceRange: PriceRange.budget,
    categories: ['footwear', 'tops', 'accessories'],
    logo: 'https://picsum.photos/seed/vans-logo/200/200',
    verified: true,
  },
  {
    name: 'New Balance',
    slug: 'new-balance',
    description: '美国跑鞋品牌，舒适缓震科技',
    priceRange: PriceRange.mid_range,
    categories: ['footwear', 'activewear'],
    logo: 'https://picsum.photos/seed/nb-logo/200/200',
    verified: true,
  },
  {
    name: 'ASICS',
    slug: 'asics',
    description: '日本专业跑鞋品牌，GEL缓震科技',
    priceRange: PriceRange.mid_range,
    categories: ['footwear', 'activewear'],
    logo: 'https://picsum.photos/seed/asics-logo/200/200',
    verified: true,
  },
  // === Accessories/Bags ===
  {
    name: 'FURLA',
    slug: 'furla',
    description: '意大利皮具品牌，优雅包袋',
    priceRange: PriceRange.premium,
    categories: ['accessories'],
    logo: 'https://picsum.photos/seed/furla-logo/200/200',
    verified: true,
  },
  {
    name: 'Longchamp',
    slug: 'longchamp',
    description: '法国皮具品牌，经典折叠包',
    priceRange: PriceRange.premium,
    categories: ['accessories'],
    logo: 'https://picsum.photos/seed/longchamp-logo/200/200',
    verified: true,
  },
  {
    name: 'Coach',
    slug: 'coach',
    description: '美国轻奢品牌，经典皮革包袋',
    priceRange: PriceRange.premium,
    categories: ['accessories'],
    logo: 'https://picsum.photos/seed/coach-logo/200/200',
    verified: true,
  },
  {
    name: 'Michael Kors',
    slug: 'michael-kors',
    description: '美国轻奢品牌，Jet Set生活方式',
    priceRange: PriceRange.premium,
    categories: ['accessories'],
    logo: 'https://picsum.photos/seed/mk-logo/200/200',
    verified: true,
  },
  // === Designer/Independent ===
  {
    name: 'Acne Studios',
    slug: 'acne-studios',
    description: '瑞典设计师品牌，极简北欧风格',
    priceRange: PriceRange.premium,
    categories: ['tops', 'bottoms', 'outerwear', 'accessories'],
    logo: 'https://picsum.photos/seed/acne-logo/200/200',
    verified: true,
  },
  {
    name: 'MM6 Maison Margiela',
    slug: 'mm6',
    description: 'Maison Margiela副线品牌，先锋设计',
    priceRange: PriceRange.premium,
    categories: ['tops', 'dresses', 'footwear', 'accessories'],
    logo: 'https://picsum.photos/seed/mm6-logo/200/200',
    verified: true,
  },
  {
    name: 'KENZO',
    slug: 'kenzo',
    description: '法国日裔设计师品牌，大胆印花',
    priceRange: PriceRange.premium,
    categories: ['tops', 'dresses', 'footwear', 'accessories'],
    logo: 'https://picsum.photos/seed/kenzo-logo/200/200',
    verified: true,
  },
  // === Swimwear specialty ===
  {
    name: 'Speedo',
    slug: 'speedo',
    description: '全球领先泳装品牌，专业水上运动',
    priceRange: PriceRange.mid_range,
    categories: ['swimwear', 'accessories'],
    logo: 'https://picsum.photos/seed/speedo-logo/200/200',
    verified: true,
  },
  {
    name: 'Roxy',
    slug: 'roxy',
    description: '女性冲浪运动品牌，海滩生活方式',
    priceRange: PriceRange.mid_range,
    categories: ['swimwear', 'tops', 'bottoms', 'accessories'],
    logo: 'https://picsum.photos/seed/roxy-logo/200/200',
    verified: true,
  },
];

export async function seedBrands(prisma: PrismaClient): Promise<{ brands: any[], brandMap: Map<string, any> }> {
  const results = [];

  for (const brand of brands) {
    const result = await prisma.brand.upsert({
      where: { slug: brand.slug },
      update: {
        name: brand.name,
        description: brand.description,
        priceRange: brand.priceRange,
        categories: brand.categories,
        website: brand.website ?? null,
        logo: brand.logo ?? null,
        verified: brand.verified ?? false,
      },
      create: {
        name: brand.name,
        slug: brand.slug,
        description: brand.description,
        priceRange: brand.priceRange,
        categories: brand.categories,
        website: brand.website ?? null,
        logo: brand.logo ?? null,
        verified: brand.verified ?? false,
      },
    });
    results.push(result);
  }

  const brandMap = new Map<string, any>();
  for (const brand of results) {
    brandMap.set(brand.slug, brand);
  }

  return { brands: results, brandMap };
}
