import type { DesignTokens } from "./tokens/design-tokens";

type TokenSet = typeof DesignTokens;

type BrandColors = TokenSet["colors"]["brand"] & {
  primary: string;
  warmPrimary: string;
  warmAccent: string;
  warmSecondary: string;
};

type GradientColors = TokenSet["gradients"] & {
  warm: string[];
  cool: string[];
  hero: string[];
  coralRose: string[];
  oceanMint: string[];
};

export interface FlatColors {
  brand: BrandColors;
  neutral: TokenSet["colors"]["neutral"];
  semantic: TokenSet["colors"]["semantic"] & {
    successDark: string;
    warningDark: string;
    errorDark: string;
    like: string;
    bookmark: string;
    chartGood: string;
    chartMedium: string;
    chartPoor: string;
    chartGrid: string;
    skeletonBase: string;
    warmBlush: string;
    slateMist: string;
    goldenGlow: string;
    sageMist: string;
    yellow: string;
    brown: string;
    wechat: string;
    weibo: string;
    qq: string;
    mutedSage: string;
    fashion: TokenSet["colors"]["fashion"];
  };
  backgrounds: TokenSet["colors"]["backgrounds"];
  text: TokenSet["colors"]["text"];
  borders: TokenSet["colors"]["borders"];
  colorSeasons: TokenSet["colors"]["colorSeasons"];
  surface: string;
  surfaceSecondary: string;
  surfaceTertiary: string;
  surfaceElevated: string;
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textInverse: string;
  textBrand: string;
  border: string;
  borderLight: string;
  borderStrong: string;
  borderBrand: string;
  primary: string;
  primaryLight: string;
  primaryDark: string;
  subtleBg: string;
  gold: string;
  placeholderBg: string;
  overlay: string;
  background: string;
  backgroundSecondary: string;
  backgroundTertiary: string;
  error: string;
  errorLight: string;
  success: string;
  successLight: string;
  warning: string;
  warningLight: string;
  info: string;
  infoLight: string;
  divider: string;
  cartLight: string;
  terracottaDark: string;
  amber: string;
  secondary: string;
  secondaryLight: string;
  warmPrimary: string;
  warmAccent: string;
  warmSecondary: string;
  like: string;
  ocean: string;
  mint: string;
  coral: string;
  main: string;
  light: string;
  dark: string;
  oceanMint: string;
  fashion: string;
  purple: string;
  gradients: GradientColors;
}
